FROM markoshust/magento-nginx:1.24-0
# Decoment to set up multiple websites with Nginx using virtual hosts (simplified):
# https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/multi-sites/ms-nginx.html?lang=en
#COPY --chown=app:app ./conf/default.conf /etc/nginx/conf.d/